version: '3'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: azerty123
      POSTGRES_DB: rentmyhouse
    ports:
      - '7140:5432'
  redis:
    image: 'redis:7.0-alpine'
    ports:
      - '7141:6379'
  mailer:
    image: 'mailhog/mailhog'
    ports:
      - '7142:1025'
      - '7143:8025'
  dbadmin:
    image: 'dpage/pgadmin4'
    environment:
      PGADMIN_DEFAULT_EMAIL: contact@rentmyhouse.fr
      PGADMIN_DEFAULT_PASSWORD: azerty123
    ports:
      - '7144:80'